version: "3.3"
services:
        
  stg2_pivot:
    build: ./stg2_pivot
    environment:
      SCALA_VERSION: 2.12.8
      SBT_VERSION: 1.2.7

networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
